#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

/** @var Composer\Autoload\ClassLoader $loader */
$loader = require __DIR__ . '/autoload.php';

$input = new ArgvInput();
$env   = $input->getParameterOption(array('--env', '-e'), (getenv('SYMFONY_ENV') ?: 'dev'));
$debug = !$input->hasParameterOption(array('--no-debug', ''));

$kernel      = new MongoDBAppKernel($env, $debug);
$application = new Application($kernel);
$application->run();
